server:
  port: 8761

spring:
  application:
    name: eserver

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    peerNodeReadTimeoutMs: 10000
  instance:
    hostname: localhost