server:
  port: 8081

spring:
  application:
    name: frontend

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://eserver:8761/eureka/

posts:
  url: http://posts/user/add-user

chat:
  url: http://chat-app/user/add-user