version: "3.3"

services:
  # mysqldb:
  #   image: mysql
  #   environment:
  #     - MYSQL_USER=collreach
  #     - MYSQL_PASSWORD=Sensitive@1
  #     - MYSQL_ROOT_PASSWORD=Sensitive@1
  #   restart: always
  #   ports:
  #     - "6033:3306"
  #   volumes:
  #     - db_vol:/var/lib/mysql
  
  p_sql:
    image: custom/psql:version2
    environment: 
      - POSTGRES_USER=collreach
      - POSTGRES_PASSWORD=Sensitive@1
    ports:
      - "1234:5432"
    volumes: 
      - db_vol:/var/lib/postgresql/data

  mongo_db:
    image: mongo
    # image: custom/mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=collreach
      - MONGO_INITDB_ROOT_PASSWORD=collReach
      - MONGO_INITDB_DATABASE=collreach_chat
    ports:
      - "27018:27017"
    volumes:
      - db_vol:/data/db

  # ftp_server:
  #   image: stilliard/pure-ftpd
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "21:21"
  #     - "20:20"
  #     - "30000-30009:30000-30009"
  #   volumes:
  #     - ftp_vol:/htdocs/frontend/images/
  #   environment:
  #     PUBLICHOST: "0.0.0.0"
  #     FTP_USER_NAME: collreach
  #     FTP_USER_PASS: Sensitive@1
  #     FTP_MAX_CLIENTS: 50
  #     FTP_MAX_CONNECTIONS: 100
  #     FTP_USER_HOME: /htdocs/frontend/images/
  #   restart: always

  # ftps_client:
  #   image: jlesage/filezilla
  #   ports:
  #     - "5800:5800"
  #   links:
  #     - ftp_server

  eserver:
    build: ./eserver
    ports:
      - "8761:8761"

  userprofile:
    build: ./userprofile
    ports:
      - "8082:8082"
    restart: always
    # links:
    #   - mysqldb
    depends_on:
      # - mysqldb
      - p_sql
      - eserver
      #- ftp_server

  posts:
    build: ./posts
    ports:
      - "8084:8084"
    restart: always
    # links:
    #   - mysqldb
    depends_on:
      # - mysqldb
      - p_sql
      - eserver

  chat-app:
    build: ./chat
    ports:
      - "8083:8083"
    links:
      - mongo_db
    depends_on:
      - mongo_db
      - eserver

  gateway:
    build: ./gateway
    ports:
      - "8085:80"
    depends_on: 
      - userprofile
      - chat-app
      - posts
      - eserver

  frontend:
    build: ./frontend/
    ports:
      - "8081:8081"
    depends_on: 
      - userprofile
      - chat-app
      - posts
      - eserver
      - gateway

volumes: 
  db_vol:
  ftp_vol:

networks:
  default:
    external: true
    name: collreach1