version: "3.3"

services:
  # mysqldb:
  #   image: mysql
  #   environment:
  #     - MYSQL_USER=collreach
  #     - MYSQL_PASSWORD=Sensitive@1
  #     - MYSQL_ROOT_PASSWORD=Sensitive@1
  #   restart: always
  #   ports:
  #     - "6033:3306"
  #   volumes:
  #     - db_vol:/var/lib/mysql
  
  # psql:
  #   image: custom_psql/psql
  #   environment: 
  #     - POSTGRES_USER=collreach
  #     - POSTGRES_PASSWORD=Sensitive@1
  #   ports:
  #     - "1234:5432"

  mongo_db:
    image: mongo
    # image: custom/mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=collreach
      - MONGO_INITDB_ROOT_PASSWORD=collReach
    ports:
      - "27018:27017"
    volumes:
      - db_vol:/data/db

  ftp_server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      -  ftp_vol:/ftp/users/data
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: collreach
      FTP_USER_PASS: Sensitive@1
      FTP_USER_HOME: /htdocs/frontend/images/
    restart: always

  eserver:
    build: ./eserver
    ports:
      - "8761:8761"

  userprofile:
    build: ./userprofile
    ports:
      - "8082:8082"
    restart: always
    # links:
    #   - mysqldb
    depends_on:
      # - mysqldb
      - ftp_server
      - eserver

  posts:
    build: ./posts
    ports:
      - "8084:8084"
    restart: always
    # links:
    #   - mysqldb
    depends_on:
      # - mysqldb
      - eserver

  chat-app:
    build: ./chat
    ports:
      - "8083:8083"
    links:
      - mongo_db
    depends_on:
      - mongo_db
      - eserver

  gateway:
    build: ./gateway
    ports:
      - "8085:80"
    depends_on: 
      - userprofile
      - chat-app
      - posts
      - eserver

  frontend:
    build: ./frontend/
    ports:
      - "8081:8081"
    depends_on: 
      - userprofile
      - chat-app
      - posts
      - eserver
      - gateway

volumes: 
  db_vol:
  ftp_vol:

networks:
  default:
    external: true
    name: collreach1