server:
  port: 8082

ops: window

jwt:
  secret: secretKeyToBeChangedInFuture

images:
  server-address: http://localhost:8081/images/
  default-image: http://localhost:8081/images/default.jpeg

#ftp:
#  host: ftp.unaux.com
#  user: unaux_27598440
#  pwd: 689j616h7yuiwu
#  host-dir: /htdocs/frontend/images/
#  img-address-server: http://maybelater.unaux.com/frontend/images
#  default-img: default.jpeg
#  mini-default-img: mini_default.jpeg

ftp:
  host: ftp_server
  user: collreach
  pwd: Sensitive@1
  host-dir: /htdocs/frontend/images/
  img-address-server: http://ftp_server/htdocs/frontend/images
  default-img: default.jpeg
  mini-default-img: mini_default.jpeg


spring:
  application:
    name: userprofile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    #url: jdbc:mysql://mysqldb:3306/collreach_userlogin?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    url: jdbc:postgresql://psql:5432/collreach_userlogin?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: collreach
    password: Sensitive@1
  security:
    user:
      name: ayush
      password: pass
      roles: manager
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://eserver:8761/eureka/

# eureka:
#   client:
#     serviceUrl:
#       defaultZone=${EUREKA_SERVER:http://eserver:8761/eureka}

posts:
  url: http://posts/user/add-user

chat:
  url: http://chat-app/user/add-user

frontend:
  url: http://frontend:8081

gateway:
  url: http://gateway