server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
        - id: frontend-route
          uri: lb://frontend
          predicates:
            - Path=/in/**
        - id: userprofile-route
          uri: lb://userprofile
          predicates:
            - Path=/userprofile/**
        - id: chat-app-route
          uri: lb://chat-app
          predicates:
            - Path=/chat/**
        - id: posts-route
          uri: lb://posts
          predicates:
            - Path=/posts/**
        - id: eureka-route
          uri: lb://eserver
          predicates:
            - Path=/eserver/**
management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka