server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
        - id: frontend-route
          uri: lb://frontend
          predicates:
            - Path=/**
        - id: userprofile-route
          uri: lb://userprofile
          predicates:
            - Path=/userprofile/**
        - id: chat-app-route
          uri: lb://chat-app
          predicates:
            - Path=/chat/**
        - id: posts-route
          uri: lb://posts
          predicates:
            - Path=/posts/**
        - id: eureka-route
          uri: lb://eserver
          predicates:
            - Path=/eserver/**
management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    serviceURL:
      defaultZone: http://eserver:8761/eureka/

# gateway_1      | 2021-07-25 17:14:16.712  INFO 1 --- [tbeatExecutor-0]
#  c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. 
# endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8761/eureka/},
#  exception=I/O error on PUT request for 
# "http://localhost:8761/eureka/apps/GATEWAY/638e8c1ba8fc:gateway:80":
#  Connection refused (Connection refused); nested exception is java.net.ConnectException:
#  Connection refused (Connection refused) stacktrace=org.springframework.web.client.ResourceAccessException: 
# I/O error on PUT request for "http://localhost:8761/eureka/apps/GATEWAY/638e8c1ba8fc:gateway:80":
#  Connection refused (Connection refused); nested exception is java.net.ConnectException: 
# Connection refused (Connection refused)